[auth]
enabled = true
site_url = "https://your-production-domain.com"
additional_redirect_urls = ["https://your-production-domain.com"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400

[auth.email.template]

[auth.sms]
enable_signup = false



# stripe webhook url
# https://ldnkaktvtgolkmmpcmae.supabase.co/functions/v1/stripe-webhook
# customer.subscription.created
# customer.subscription.deleted
# customer.subscription.updated
# invoice.payment_failed